import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case ar
    case zh
    case en
    case fr
    case ru
    case es

    var id: String { rawValue }

    var resolved: AppLanguage {
        if self != .system { return self }
        let code = Locale.preferredLanguages.first ?? "en"
        if code.hasPrefix("ar") { return .ar }
        if code.hasPrefix("zh") { return .zh }
        if code.hasPrefix("fr") { return .fr }
        if code.hasPrefix("ru") { return .ru }
        if code.hasPrefix("es") { return .es }
        return .en
    }

    var layoutDirection: LayoutDirection {
        resolved == .ar ? .rightToLeft : .leftToRight
    }

    var locale: Locale {
        switch resolved {
        case .ar: return Locale(identifier: "ar")
        case .zh: return Locale(identifier: "zh_CN")
        case .fr: return Locale(identifier: "fr_FR")
        case .ru: return Locale(identifier: "ru_RU")
        case .es: return Locale(identifier: "es_ES")
        default: return Locale(identifier: "en_US")
        }
    }

    var nativeName: String {
        switch self {
        case .system: return L10n.s(.followSystem)
        case .ar: return "العربية"
        case .zh: return "中文"
        case .en: return "English"
        case .fr: return "Français"
        case .ru: return "Русский"
        case .es: return "Español"
        }
    }
}

enum LKey: String {
    case settingsWindow, settings, closeWindow, quit, usage, usageSubtitle, refreshHelp
    case sectionData, liveToggle, liveHelp, refreshInterval, refreshOnWake, refreshOnWakeHelp, minutesValue
    case sectionMenu, iconStyle, showBattery, batteryHelp, batteryInterval, batteryIntervalHelp, powerSaverOn
    case textTemplateLabel, textTemplateHelp, tokenName, tokenPercent, tokenCountdown, tokenWindow, tokenReset
    case batteryChoice, batteryIconOnly, batteryPercentOnly
    case sectionPlace, placeLabel, placeRight, placeLeft, placeFarRight, placeFarLeft, placeHelp
    case sectionAlert, alertToggle, alertLevel, alertHelp, launchLogin, launchOn, launchDenied
    case sectionLanguage, languageLabel, followSystem, languageHelp
    case sectionNotes, noteStyles, notePrivacy, noteAccounts
    case preview, addBar, addRing, hintBars, hintRings, hintCombined, meaning, colorLabel
    case styleText, styleBattery, styleBars, styleRing, styleRings, styleCombined
    case detailText, detailBattery, detailBars, detailRing, detailRings, detailCombined
    case batteryPercent, charging, onBattery, noBatteryDevice, noBatteryShort
    case batteryChargingHelp, batteryIdleHelp
    case exhausted, creditsLine, remainingWord, noReset, usedLine
    case helpLeft, helpLeftReset, accountLine, noUsageYet
    case resetSoon, shortDH, shortHM, shortM, longDH, longHM, longM
    case todayAt, tomorrowAt, dateAt, justNow, secsAgo, minsAgo, hoursAgo, daysAgo
    case fiveHours, sevenDays, hours24, nDays, nHours
    case thisMonth, onDemand, monthRequests, opusWeek, sonnetWeek, haikuWeek, extraUsage
    case shortWindow, longWindow, otherQuota, batteryName
    case noBatteryData, batteryStateLine, noSlotData, remainLine
    case unlimited, localNote, dollarNote
    case alertTitle, alertBody, alertBodyPlain
    case reading, official, localCodex, noUsageCodex
    case gptUnauthorized, gptExpired, gptMissing, gptAPIKey, gptUnreadable
    case gptHTTP, gptTemporary, gptOffline, gptTimeout, gptUnreachable
    case cursorNoLogin, cursorEmpty, cursorUnauthorized, cursorHTTP, cursorTemporary
    case cursorOffline, cursorTimeout, cursorUnreachable
    case claudeUnauthorized, claudeExpired, claudeAPIKey, claudeMissing, claudeUnreadable
    case claude429, claudeHTTP, claudeTemporary, claudeOffline, claudeTimeout, claudeUnreachable
    case checkingUpdates, updateAvailable, upToDate, updateCheckFailed, openRelease
    case pausedUpdates, staleReading, unavailable, lastAttempt, formatChanged, cursorConflict
    case providerHelp, loginHelp, diagnostics, diagnosticsHelp, welcomeTitle, welcomeHelp, getStarted, releases
    case listSep, pair
}

enum L10n {
    static var language: AppLanguage = {
        let raw = UserDefaults.standard.string(forKey: "appLanguage") ?? ""
        return AppLanguage(rawValue: raw) ?? .system
    }()

    static var period: String { language.resolved == .zh ? "。" : ". " }

    static func s(_ key: LKey, _ choice: AppLanguage? = nil) -> String {
        let lang = (choice ?? language).resolved
        return pack(lang)[key] ?? pack(.en)[key] ?? key.rawValue
    }

    static func f(_ key: LKey, _ args: CVarArg...) -> String {
        String(format: s(key), locale: language.resolved.locale, arguments: args)
    }

    static func windowTitle(_ window: UsageWindow) -> String {
        switch window.id {
        case "cursor-total": return s(.thisMonth)
        case "cursor-auto": return "Auto"
        case "cursor-api": return "API"
        case "cursor-ondemand": return s(.onDemand)
        case "cursor-requests": return s(.monthRequests)
        case "five_hour": return s(.fiveHours)
        case "seven_day": return s(.sevenDays)
        case "seven_day_opus": return s(.opusWeek)
        case "seven_day_sonnet": return s(.sonnetWeek)
        case "seven_day_haiku": return s(.haikuWeek)
        case "extra_usage": return s(.extraUsage)
        default:
            if window.id.hasPrefix("extra-") {
                if window.id.hasSuffix("primary") || window.id.hasSuffix("secondary") {
                    let role = window.id.hasSuffix("primary") ? "primary" : "secondary"
                    return window.title + " · " + duration(window.windowSeconds, id: role)
                }
                return window.title
            }
            if window.id == "primary" || window.id == "secondary" {
                return duration(window.windowSeconds, id: window.id)
            }
            return window.title
        }
    }

    static func barTitle(id: String, accounts: [ProviderAccount]) -> String {
        if id == "battery" { return s(.batteryName) }
        let parts = id.split(separator: ".", maxSplits: 1).map(String.init)
        guard parts.count == 2 else { return id }
        let accountName = accounts.first { $0.id == parts[0] }?.name ?? parts[0]
        if let window = accounts.first(where: { $0.id == parts[0] })?.windows.first(where: { $0.id == parts[1] }) {
            return f(.pair, accountName, windowTitle(window))
        }
        let label: String
        switch parts[1] {
        case "primary": label = s(.fiveHours)
        case "secondary": label = s(.sevenDays)
        case "cursor-total": label = s(.thisMonth)
        case "cursor-auto": label = "Auto"
        case "cursor-api": label = "API"
        case "cursor-ondemand": label = s(.onDemand)
        case "cursor-requests": label = s(.monthRequests)
        case "five_hour": label = s(.fiveHours)
        case "seven_day": label = s(.sevenDays)
        case "seven_day_opus": label = s(.opusWeek)
        case "seven_day_sonnet": label = s(.sonnetWeek)
        default: label = parts[1]
        }
        return f(.pair, accountName, label)
    }

    private static func duration(_ seconds: TimeInterval?, id: String) -> String {
        guard let seconds else {
            return id == "primary" ? s(.shortWindow) : s(.longWindow)
        }
        let minutes = Int((seconds / 60).rounded())
        switch minutes {
        case 300: return s(.fiveHours)
        case 10_080: return s(.sevenDays)
        case 1_440: return s(.hours24)
        default:
            if minutes >= 1_440, minutes % 1_440 == 0 { return f(.nDays, minutes / 1_440) }
            if minutes >= 60, minutes % 60 == 0 { return f(.nHours, minutes / 60) }
            return id == "primary" ? s(.shortWindow) : s(.longWindow)
        }
    }

    private static func pack(_ language: AppLanguage) -> [LKey: String] {
        switch language {
        case .zh: return zh
        case .fr: return fr
        case .ru: return ru
        case .es: return es
        case .ar: return ar
        default: return en
        }
    }
}

private let en: [LKey: String] = [
    .checkingUpdates: "Checking releases…",
    .updateAvailable: "Version %@ is available.",
    .upToDate: "You have the latest released version or a newer build.",
    .updateCheckFailed: "Could not check for updates. You can open Releases manually.",
    .openRelease: "Open Releases",
    .pausedUpdates: "Updates paused",
    .staleReading: "Historical reading",
    .unavailable: "Unavailable",
    .lastAttempt: "Last attempt: %@",
    .formatChanged: "The usage response format has changed. See login help or report a compatibility issue.",
    .cursorConflict: "Cursor's message disagrees with the numeric budget. The numeric fields are shown.",
    .providerHelp: "Enable each service separately. Paused services keep their last reading in the panel and are hidden from menu bar quota indicators. Manual refresh also respects these switches.",
    .loginHelp: "Login help",
    .diagnostics: "Export diagnostics…",
    .diagnosticsHelp: "Exports service states, times and window counts. No tokens, account identifiers, emails, conversation contents or usage values are included.",
    .welcomeTitle: "Welcome to MacTokenGauge",
    .welcomeHelp: "Choose the services you use. ChatGPT reads CODEX_HOME/auth.json (normally ~/.codex/auth.json); Cursor reads its local state database; Claude reads local credentials or its Keychain entry. Tokens go only to the corresponding service. Local Codex logs are used only when they explicitly identify the current account. No login files are changed.",
    .getStarted: "Get started",
    .releases: "Check releases…",
    .settingsWindow: "MacTokenGauge",
    .settings: "Settings",
    .closeWindow: "Close Window",
    .quit: "Quit",
    .usage: "Usage",
    .usageSubtitle: "ChatGPT, Cursor, and Claude are shown together. The percent is what remains.",
    .refreshHelp: "Read usage again",
    .sectionData: "Data",
    .liveToggle: "Read official usage",
    .liveHelp: "ChatGPT reads the official site on this interval and keeps that reading. Local records appear only before the site has returned a number. The switch still controls Cursor and Claude.",
    .refreshInterval: "Refresh interval",
    .refreshOnWake: "Refresh when the screen turns on",
    .refreshOnWakeHelp: "Also refresh usage when the screen turns on, including when the lid is opened. Launching the app always refreshes once, whether this is on or off.",
    .minutesValue: "%d min",
    .sectionMenu: "Menu bar",
    .iconStyle: "Icon style",
    .showBattery: "Show this Mac’s battery",
    .batteryHelp: "Whenever the menu bar shows the battery, choose the icon or the percent. The panel still shows both.",
    .batteryInterval: "Battery check",
    .batteryIntervalHelp: "How often the battery percentage is read.",
    .powerSaverOn: "Low Power Mode or a low-battery warning is on, so usage checks, the menu bar clock, and battery reads all slow down until it ends.",
    .textTemplateLabel: "Menu bar text",
    .textTemplateHelp: "Type the words yourself. {name} is the account, {percent} is what remains, {countdown} is the time until reset, {window} is the quota name, and {reset} is the clock time. Each account that has a reading uses this same text.",
    .tokenName: "Account",
    .tokenPercent: "Remaining",
    .tokenCountdown: "Countdown",
    .tokenWindow: "Window",
    .tokenReset: "Reset time",
    .batteryChoice: "Battery shows",
    .batteryIconOnly: "Icon only",
    .batteryPercentOnly: "Percent only",
    .sectionPlace: "Position",
    .placeLabel: "Icon position",
    .placeRight: "Right",
    .placeLeft: "Left",
    .placeFarRight: "Far right",
    .placeFarLeft: "Far left",
    .placeHelp: "The clock, Control Center, Wi-Fi, and other apps already occupy the right side. This app cannot push them aside. Hold Command and drag this icon to move it among the other apps. The furthest it can go is just to the left of Control Center.",
    .sectionAlert: "Alerts",
    .alertToggle: "Notify when remaining is low",
    .alertLevel: "Alert threshold",
    .alertHelp: "When a window falls to this remaining share and still has some left, you get one notification. If a check finds that window already used up, there is no notification. It will not repeat in the same reset cycle.",
    .launchLogin: "Open at login",
    .launchOn: "It will open at login. If the system blocks it, move the app into the Applications folder and try again.",
    .launchDenied: "The system did not allow opening at login: %@",
    .sectionLanguage: "Language",
    .languageLabel: "Display language",
    .followSystem: "Follow system",
    .languageHelp: "Follow system uses Arabic, Chinese, English, French, Russian, or Spanish when that is your Mac’s language. Otherwise it uses English. You can also pick one of the six United Nations official languages here.",
    .sectionNotes: "Notes",
    .noteStyles: "Text style lists the accounts that have been read. The percent is what remains, and the time is when that window resets. Orange and red mean the window is running low.",
    .notePrivacy: "Login is read only on this Mac, and only to check usage. The app does not write tokens back, and it does not send conversation contents.",
    .noteAccounts: "ChatGPT reads the login already saved by the ChatGPT app, then asks the official site for usage. Cursor uses the current Cursor login. Claude’s 5-hour and 7-day windows need a subscription login. An API key alone does not show those windows.",
    .preview: "Preview",
    .addBar: "Add a bar",
    .addRing: "Add a ring",
    .hintBars: "Top to bottom is the order of the bars in the menu bar. Each bar can be a quota or the battery, with its own color. Up to six.",
    .hintRings: "Left to right is the order of the small rings. Each ring can be a quota or the battery, with its own color. Up to six.",
    .hintCombined: "Top to bottom, the first row is the outer ring. Each ring can be a quota or the battery, with its own color. Up to six.",
    .meaning: "Meaning",
    .colorLabel: "Color",
    .styleText: "Text",
    .styleBattery: "Battery only",
    .styleBars: "Colored bars",
    .styleRing: "Single ring",
    .styleRings: "Multiple rings",
    .styleCombined: "Combined ring",
    .detailText: "Shows the account name, remaining percent, and reset countdown.",
    .detailBattery: "Shows only this Mac’s battery, as an icon or a percent, using the choice above.",
    .detailBars: "Each bar is one quota. A longer bar means more remaining. You can change the meaning and the color.",
    .detailRing: "Keeps only the tightest window, shown as one ring and a percent, without the account name.",
    .detailRings: "Each quota gets its own small ring, side by side. Meaning and color are shared with the colored bars.",
    .detailCombined: "Draws those quotas as concentric rings in one icon. The first row is the outer ring.",
    .batteryPercent: "Battery %d%%",
    .charging: "Charging",
    .onBattery: "On battery",
    .noBatteryDevice: "This Mac has no battery.",
    .noBatteryShort: "No battery",
    .batteryChargingHelp: "Battery %d%%, charging",
    .batteryIdleHelp: "Battery %d%%",
    .exhausted: "%@ is used up. It stays unavailable until the reset time.",
    .creditsLine: "Credits %@",
    .remainingWord: "left",
    .noReset: "No reset time yet",
    .usedLine: "Used %d%%",
    .helpLeft: "%@ has %d%% left",
    .helpLeftReset: "%@ has %d%% left, resets %@",
    .accountLine: "%@: %@",
    .noUsageYet: "No usage yet",
    .resetSoon: "resets soon",
    .shortDH: "%dd %dh",
    .shortHM: "%dh %dm",
    .shortM: "%dm",
    .longDH: "Resets in %dd %dh",
    .longHM: "Resets in %dh %dm",
    .longM: "Resets in %dm",
    .todayAt: "Today %@",
    .tomorrowAt: "Tomorrow %@",
    .dateAt: "%@ %@",
    .justNow: "Updated just now",
    .secsAgo: "Updated %d sec ago",
    .minsAgo: "Updated %d min ago",
    .hoursAgo: "Updated %d hr ago",
    .daysAgo: "Updated %d d ago",
    .fiveHours: "5 hours",
    .sevenDays: "7 days",
    .hours24: "24 hours",
    .nDays: "%d days",
    .nHours: "%d hours",
    .thisMonth: "This month",
    .onDemand: "On-demand",
    .monthRequests: "Monthly requests",
    .opusWeek: "Opus weekly",
    .sonnetWeek: "Sonnet weekly",
    .haikuWeek: "Haiku weekly",
    .extraUsage: "Extra usage",
    .shortWindow: "Short window",
    .longWindow: "Long window",
    .otherQuota: "Other quota",
    .batteryName: "Battery",
    .noBatteryData: "No battery data yet",
    .batteryStateLine: "%d%%, %@",
    .noSlotData: "No data yet",
    .remainLine: "%d%% left",
    .unlimited: "Unlimited",
    .localNote: "From local records",
    .dollarNote: "Included usage %@ USD, limit %@ USD",
    .alertTitle: "%@ usage is low",
    .alertBody: "%@ has %d%% left, %@.",
    .alertBodyPlain: "%@ has %d%% left.",
    .reading: "Reading",
    .official: "Official usage",
    .localCodex: "The official site has not returned usage yet, so this shows the last numbers saved on this Mac.",
    .noUsageCodex: "No usage yet. Open the ChatGPT app and sign in.",
    .gptUnauthorized: "The login has expired. Open Codex once and let it refresh the login itself. This app will not rewrite the login file.",
    .gptExpired: "The login has expired. Open Codex once, let it refresh the login, then try again. This app will not rewrite the login file.",
    .gptMissing: "The ChatGPT app has no saved login yet. Open ChatGPT and sign in.",
    .gptAPIKey: "This is an API key login, so there is no ChatGPT subscription window. Use codex login instead.",
    .gptUnreadable: "The local login file cannot be read.",
    .gptHTTP: "The usage service returned %d. Showing the local record for now.",
    .gptTemporary: "Official usage cannot be read right now. Showing the local record for now.",
    .gptOffline: "No network. Showing the local record for now.",
    .gptTimeout: "The usage service timed out. Showing the local record for now.",
    .gptUnreachable: "The usage service cannot be reached. Showing the local record for now.",
    .cursorNoLogin: "No Cursor login was found. Sign in inside Cursor first.",
    .cursorEmpty: "The login is valid, but the usage service returned no windows.",
    .cursorUnauthorized: "The Cursor login is no longer valid. Sign in again in Cursor. This app will not change the login.",
    .cursorHTTP: "The Cursor usage service returned %d.",
    .cursorTemporary: "Cursor usage cannot be read right now.",
    .cursorOffline: "No network. Cursor usage cannot be read right now.",
    .cursorTimeout: "The Cursor usage service timed out.",
    .cursorUnreachable: "The Cursor usage service cannot be reached right now.",
    .claudeUnauthorized: "The Claude login is no longer valid. Open Claude Code once and let it refresh the login itself. This app will not change the login.",
    .claudeExpired: "The Claude login has expired. Open Claude Code once and let it refresh the login itself. This app will not change the login.",
    .claudeAPIKey: "An API key was found. There is no Claude subscription 5-hour or 7-day window. Sign in to a subscription account with claude.",
    .claudeMissing: "There is no Claude subscription login yet. Run claude in Terminal and sign in. The 5-hour and 7-day windows will appear here.",
    .claudeUnreadable: "The Claude login file cannot be read.",
    .claude429: "The Claude usage service is rate limiting. Refresh again in a few minutes.",
    .claudeHTTP: "The Claude usage service returned %d.",
    .claudeTemporary: "Claude usage cannot be read right now.",
    .claudeOffline: "No network. Claude usage cannot be read right now.",
    .claudeTimeout: "The Claude usage service timed out.",
    .claudeUnreachable: "The Claude usage service cannot be reached right now.",
    .listSep: ", ",
    .pair: "%@ · %@"
]

private let zh: [LKey: String] = [
    .checkingUpdates: "正在检查新版本……",
    .updateAvailable: "发现新版本 %@。",
    .upToDate: "当前已是最新发布版本，或较新的构建版本。",
    .updateCheckFailed: "无法检查新版本，可手动查看 Releases。",
    .openRelease: "打开 Releases",
    .pausedUpdates: "已暂停更新",
    .staleReading: "历史读数",
    .unavailable: "暂无可用数据",
    .lastAttempt: "最后尝试：%@",
    .formatChanged: "用量接口格式发生变化。请查看登录帮助，或反馈兼容问题。",
    .cursorConflict: "Cursor 文案与结构化金额不一致，当前采用结构化数字。",
    .providerHelp: "分别启用你使用的服务。暂停后，弹窗保留最后读数，菜单栏隐藏该服务的额度指示。手动刷新也遵循这些开关。",
    .loginHelp: "登录帮助",
    .diagnostics: "导出诊断信息……",
    .diagnosticsHelp: "仅导出服务状态、时间和窗口数量，不含令牌、账户标识、邮箱、对话内容或用量数值。",
    .welcomeTitle: "欢迎使用 MacTokenGauge",
    .welcomeHelp: "请选择你使用的服务。ChatGPT 读取 CODEX_HOME 下的 auth.json，默认位于 ~/.codex；Cursor 读取本地状态数据库；Claude 读取本地凭据文件或钥匙串条目。令牌仅发送至对应服务。本地 Codex 日志须能明确匹配当前账户才会使用。应用不会修改登录文件。",
    .getStarted: "开始使用",
    .releases: "查看新版本……",
    .settingsWindow: "MacTokenGauge",
    .settings: "设置",
    .closeWindow: "关闭窗口",
    .quit: "退出",
    .usage: "用量",
    .usageSubtitle: "ChatGPT、Cursor、Claude 同时显示。百分比是还剩多少。",
    .refreshHelp: "重新读取用量",
    .sectionData: "数据",
    .liveToggle: "读取官方用量",
    .liveHelp: "ChatGPT 会按这个间隔连接官网，并一直保留官网读到的数字。只有官网还没有返回过用量时，才暂时显示本机记录。上面的开关仍然控制 Cursor 和 Claude。",
    .refreshInterval: "刷新间隔",
    .refreshOnWake: "亮屏时刷新",
    .refreshOnWakeHelp: "屏幕点亮时再查一次用量，包括打开笔记本盖子。每次启动应用都会刷新一次，不受这个开关影响。",
    .minutesValue: "%d 分钟",
    .sectionMenu: "菜单栏",
    .iconStyle: "图标样式",
    .showBattery: "显示本机电量",
    .batteryHelp: "只要菜单栏显示电量，就可以只显示电池图标，或只显示百分比。面板里仍会同时显示图标和百分比。",
    .batteryInterval: "电量检查间隔",
    .batteryIntervalHelp: "多久读取一次电量百分比。",
    .powerSaverOn: "系统已开启节能，或出现低电量警告。用量检查、菜单栏时钟和电量读取都会自动放慢，结束后恢复你设置的间隔。",
    .textTemplateLabel: "菜单栏文字",
    .textTemplateHelp: "文字可以自己写。{name} 是账号，{percent} 是剩余百分比，{countdown} 是距离重置的时间，{window} 是配额名称，{reset} 是重置的钟点。每个已经读到用量的账号都会套用这段文字。",
    .tokenName: "账号",
    .tokenPercent: "剩余",
    .tokenCountdown: "倒计时",
    .tokenWindow: "窗口",
    .tokenReset: "重置时刻",
    .batteryChoice: "电量显示方式",
    .batteryIconOnly: "只显示图标",
    .batteryPercentOnly: "只显示百分比",
    .sectionPlace: "位置",
    .placeLabel: "图标位置",
    .placeRight: "靠右",
    .placeLeft: "靠左",
    .placeFarRight: "最右侧",
    .placeFarLeft: "最左侧",
    .placeHelp: "菜单栏最右侧是时钟、控制中心、无线网络，以及其他应用的图标。本应用不能把这些图标挤开。按住 Command 键拖动本图标，可以在其他应用之间调整顺序，最远只能到控制中心的左边。",
    .sectionAlert: "提醒",
    .alertToggle: "剩余偏低时通知",
    .alertLevel: "提醒阈值",
    .alertHelp: "某个窗口的剩余额度降到这个比例、而且还有剩余时，通知一次。如果某次检查时已经全部用完，就不再提醒。同一个重置周期里不会重复响。",
    .launchLogin: "登录时打开",
    .launchOn: "已设为登录时打开。如果系统拦住了，把应用拖进“应用程序”文件夹后再试一次。",
    .launchDenied: "系统没有允许开机打开：%@",
    .sectionLanguage: "语言",
    .languageLabel: "显示语言",
    .followSystem: "跟随系统",
    .languageHelp: "跟随系统时，如果 Mac 的语言是阿拉伯文、中文、英文、法文、俄文或西班牙文，就用该语言，否则用英文。也可以在这里改用这六种联合国正式语文。",
    .sectionNotes: "说明",
    .noteStyles: "文字样式会列出已经读到的账号。百分比是还剩多少，后面的时间是这个窗口多久后重置。颜色变橙、变红，表示这个窗口快用完了。",
    .notePrivacy: "登录只在本机读取，用来查询用量。应用不会把令牌写回去，也不会把对话内容发出去。",
    .noteAccounts: "ChatGPT 读取本机 ChatGPT 应用已经保存的登录，再向官网查询用量。Cursor 用当前 Cursor 登录。Claude 的 5 小时和 7 天窗口需要订阅登录。只有 API Key 时看不到这两个窗口。",
    .preview: "预览",
    .addBar: "添加一条横线",
    .addRing: "添加一枚环",
    .hintBars: "从上到下就是菜单栏里横线的顺序。每条线可以选择一种配额或电量，并单独设颜色。最多六条。",
    .hintRings: "从左到右就是菜单栏里小环的顺序。每枚环可以选择一种配额或电量，并单独设颜色。最多六枚。",
    .hintCombined: "从上到下，第一条是最外圈。每枚环可以选择一种配额或电量，并单独设颜色。最多六枚。",
    .meaning: "含义",
    .colorLabel: "颜色",
    .styleText: "文字",
    .styleBattery: "仅电量",
    .styleBars: "彩色横线",
    .styleRing: "单环",
    .styleRings: "多环",
    .styleCombined: "合成环",
    .detailText: "显示账号名、剩余百分比和重置倒计时。",
    .detailBattery: "菜单栏只显示本机电量，按上面的选择显示图标或百分比。",
    .detailBars: "每条横线代表一种配额。线越长，剩余越多。含义和颜色可以自己改。",
    .detailRing: "只留目前最紧张的那个窗口，用一枚环和百分比表示，不写账号名。",
    .detailRings: "每种配额各画一枚小环，并排显示。含义和颜色跟彩色横线共用同一套配置。",
    .detailCombined: "把这些配额画成同心圆，套在同一个图标里。最外圈是列表里的第一条。",
    .batteryPercent: "本机电量 %d%%",
    .charging: "正在充电",
    .onBattery: "正在使用电池",
    .noBatteryDevice: "这台 Mac 没有检测到电池。",
    .noBatteryShort: "无电池",
    .batteryChargingHelp: "本机电量 %d%%，正在充电",
    .batteryIdleHelp: "本机电量 %d%%",
    .exhausted: "%@已经用完。到重置时间之前，这个窗口不能继续用。",
    .creditsLine: "积分余额 %@",
    .remainingWord: "剩余",
    .noReset: "还没有重置时间",
    .usedLine: "已用 %d%%",
    .helpLeft: "%@还剩 %d%%",
    .helpLeftReset: "%@还剩 %d%%，%@重置",
    .accountLine: "%@：%@",
    .noUsageYet: "尚未读到用量",
    .resetSoon: "即将重置",
    .shortDH: "%d天%d时",
    .shortHM: "%d时%d分",
    .shortM: "%d分",
    .longDH: "%d天%d小时后重置",
    .longHM: "%d小时%d分后重置",
    .longM: "%d分钟后重置",
    .todayAt: "今天 %@",
    .tomorrowAt: "明天 %@",
    .dateAt: "%@ %@",
    .justNow: "刚刚更新",
    .secsAgo: "%d 秒前更新",
    .minsAgo: "%d 分钟前更新",
    .hoursAgo: "%d 小时前更新",
    .daysAgo: "%d 天前更新",
    .fiveHours: "5 小时",
    .sevenDays: "7 天",
    .hours24: "24 小时",
    .nDays: "%d 天",
    .nHours: "%d 小时",
    .thisMonth: "本月",
    .onDemand: "按量",
    .monthRequests: "本月请求",
    .opusWeek: "Opus 每周",
    .sonnetWeek: "Sonnet 每周",
    .haikuWeek: "Haiku 每周",
    .extraUsage: "额外用量",
    .shortWindow: "短时窗口",
    .longWindow: "长时窗口",
    .otherQuota: "其他额度",
    .batteryName: "本机电量",
    .noBatteryData: "还没有电池数据",
    .batteryStateLine: "%d%%，%@",
    .noSlotData: "还没有数据",
    .remainLine: "剩余 %d%%",
    .unlimited: "不限",
    .localNote: "来自本机记录",
    .dollarNote: "包含额度已用 %@ 美元，上限 %@ 美元",
    .alertTitle: "%@ 用量偏低",
    .alertBody: "%@还剩 %d%%，%@。",
    .alertBodyPlain: "%@还剩 %d%%。",
    .reading: "正在读取",
    .official: "官方用量",
    .localCodex: "官网还没有返回用量，所以先显示这台 Mac 上一次记下的数字。",
    .noUsageCodex: "还没有读到用量。请先打开 ChatGPT 应用并登录。",
    .gptUnauthorized: "登录已失效。请打开一次 Codex，让它自己刷新登录。本应用不会改写登录文件。",
    .gptExpired: "登录已过期。请打开一次 Codex，让它自己刷新登录后再试。本应用不会改写登录文件。",
    .gptMissing: "还没有读到 ChatGPT 应用保存的登录。请先打开 ChatGPT 并登录。",
    .gptAPIKey: "当前是 API Key 登录，没有 ChatGPT 订阅用量窗口。请改用 codex login。",
    .gptUnreadable: "本机登录文件无法读取。",
    .gptHTTP: "用量服务返回 %d，先显示本机记录。",
    .gptTemporary: "暂时读不到官方用量，先显示本机记录。",
    .gptOffline: "没有网络，先显示本机记录。",
    .gptTimeout: "用量服务超时，先显示本机记录。",
    .gptUnreachable: "暂时连不上用量服务，先显示本机记录。",
    .cursorNoLogin: "还没有读到 Cursor 登录。请先在 Cursor 里登录账号。",
    .cursorEmpty: "登录有效，但用量接口没有返回窗口。",
    .cursorUnauthorized: "Cursor 登录已失效。请在 Cursor 里重新登录。本应用不会改写登录。",
    .cursorHTTP: "Cursor 用量服务返回 %d。",
    .cursorTemporary: "暂时读不到 Cursor 用量。",
    .cursorOffline: "没有网络，Cursor 用量暂时读不到。",
    .cursorTimeout: "Cursor 用量服务超时。",
    .cursorUnreachable: "暂时连不上 Cursor 用量服务。",
    .claudeUnauthorized: "Claude 登录已失效。请打开一次 Claude Code，让它自己刷新登录。本应用不会改写登录。",
    .claudeExpired: "Claude 登录已过期。请打开一次 Claude Code，让它自己刷新登录。本应用不会改写登录。",
    .claudeAPIKey: "检测到的是 API Key，没有 Claude 订阅的 5 小时和 7 天窗口。请用 claude 登录订阅账号。",
    .claudeMissing: "还没有 Claude 订阅登录。在终端执行 claude 登录后，这里会显示 5 小时和 7 天窗口。",
    .claudeUnreadable: "Claude 登录文件无法读取。",
    .claude429: "Claude 用量接口暂时限流，过几分钟再刷新。",
    .claudeHTTP: "Claude 用量服务返回 %d。",
    .claudeTemporary: "暂时读不到 Claude 用量。",
    .claudeOffline: "没有网络，Claude 用量暂时读不到。",
    .claudeTimeout: "Claude 用量服务超时。",
    .claudeUnreachable: "暂时连不上 Claude 用量服务。",
    .listSep: "、",
    .pair: "%@ · %@"
]

private let fr: [LKey: String] = [
    .checkingUpdates: "Recherche de versions…",
    .updateAvailable: "La version %@ est disponible.",
    .upToDate: "Vous avez la dernière version publiée ou une version plus récente.",
    .updateCheckFailed: "Impossible de vérifier les mises à jour. Consultez les versions manuellement.",
    .openRelease: "Ouvrir les versions",
    .pausedUpdates: "Actualisation suspendue",
    .staleReading: "Ancien relevé",
    .unavailable: "Données indisponibles",
    .lastAttempt: "Dernière tentative : %@",
    .formatChanged: "Le format de la réponse a changé. Consultez l’aide à la connexion ou signalez un problème de compatibilité.",
    .cursorConflict: "Le message de Cursor diffère du budget numérique. Les valeurs numériques sont affichées.",
    .providerHelp: "Activez chaque service séparément. Les services suspendus conservent leur dernier relevé dans le panneau et disparaissent des indicateurs de quota de la barre des menus. L’actualisation manuelle respecte aussi ces choix.",
    .loginHelp: "Aide à la connexion",
    .diagnostics: "Exporter les diagnostics…",
    .diagnosticsHelp: "Exporte les états, les heures et le nombre de fenêtres. Aucun jeton, identifiant de compte, e-mail, contenu de conversation ou valeur d’utilisation n’est inclus.",
    .welcomeTitle: "Bienvenue dans MacTokenGauge",
    .welcomeHelp: "Choisissez vos services. ChatGPT lit CODEX_HOME/auth.json, normalement ~/.codex/auth.json ; Cursor lit sa base locale ; Claude lit les identifiants locaux ou le trousseau. Chaque jeton est envoyé uniquement au service correspondant. Les journaux Codex doivent identifier explicitement le compte actuel. Aucun fichier de connexion n’est modifié.",
    .getStarted: "Commencer",
    .releases: "Vérifier les mises à jour…",
    .settingsWindow: "MacTokenGauge",
    .settings: "Réglages",
    .closeWindow: "Fermer la fenêtre",
    .quit: "Quitter",
    .usage: "Consommation",
    .usageSubtitle: "ChatGPT, Cursor et Claude s’affichent ensemble. Le pourcentage est ce qu’il reste.",
    .refreshHelp: "Relire la consommation",
    .sectionData: "Données",
    .liveToggle: "Lire la consommation officielle",
    .liveHelp: "ChatGPT interroge le site officiel à cet intervalle et conserve ce chiffre. Les enregistrements locaux n’apparaissent que tant que le site n’a encore rien renvoyé. L’interrupteur concerne toujours Cursor et Claude.",
    .refreshInterval: "Intervalle",
    .refreshOnWake: "Actualiser à l’allumage de l’écran",
    .refreshOnWakeHelp: "Relance aussi une lecture quand l’écran s’allume, y compris à l’ouverture du capot. Le lancement de l’app actualise toujours une fois, que ce réglage soit activé ou non.",
    .minutesValue: "%d min",
    .sectionMenu: "Barre des menus",
    .iconStyle: "Style d’icône",
    .showBattery: "Afficher la batterie de ce Mac",
    .batteryHelp: "Dès que la barre affiche la batterie, choisissez l’icône ou le pourcentage. Le panneau montre les deux.",
    .batteryInterval: "Contrôle de la batterie",
    .batteryIntervalHelp: "Fréquence de lecture du pourcentage de batterie.",
    .powerSaverOn: "Le mode économie d’énergie ou l’avertissement de batterie faible est actif. Les contrôles d’usage, l’horloge de la barre et la lecture de la batterie ralentissent jusqu’à la fin.",
    .textTemplateLabel: "Texte de la barre",
    .textTemplateHelp: "Écrivez le texte vous-même. {name} est le compte, {percent} le reste, {countdown} le délai avant réinitialisation, {window} le nom du quota, {reset} l’heure. Chaque compte déjà lu reprend ce texte.",
    .tokenName: "Compte",
    .tokenPercent: "Reste",
    .tokenCountdown: "Compte à rebours",
    .tokenWindow: "Fenêtre",
    .tokenReset: "Heure",
    .batteryChoice: "La batterie affiche",
    .batteryIconOnly: "Icône seule",
    .batteryPercentOnly: "Pourcentage seul",
    .sectionPlace: "Position",
    .placeLabel: "Position de l’icône",
    .placeRight: "Droite",
    .placeLeft: "Gauche",
    .placeFarRight: "Extrême droite",
    .placeFarLeft: "Extrême gauche",
    .placeHelp: "L’horloge, le Centre de contrôle, le Wi-Fi et d’autres apps occupent déjà la droite. Cette app ne peut pas les pousser. Maintenez Commande et faites glisser cette icône pour la placer parmi les autres. Le plus loin, c’est juste à gauche du Centre de contrôle.",
    .sectionAlert: "Alertes",
    .alertToggle: "Prévenir quand il en reste peu",
    .alertLevel: "Seuil d’alerte",
    .alertHelp: "Quand une fenêtre descend à cette part restante et qu’il en reste encore, une notification part une fois. Si une lecture trouve la fenêtre déjà épuisée, il n’y a pas de notification. Elle ne se répète pas dans le même cycle.",
    .launchLogin: "Ouvrir à l’ouverture de session",
    .launchOn: "L’app s’ouvrira à l’ouverture de session. Si le système bloque, placez l’app dans le dossier Applications puis réessayez.",
    .launchDenied: "Le système n’a pas autorisé l’ouverture à la connexion : %@",
    .sectionLanguage: "Langue",
    .languageLabel: "Langue d’affichage",
    .followSystem: "Suivre le système",
    .languageHelp: "Suivre le système utilise l’arabe, le chinois, l’anglais, le français, le russe ou l’espagnol si c’est la langue du Mac. Sinon, l’anglais. Vous pouvez aussi choisir ici l’une des six langues officielles des Nations unies.",
    .sectionNotes: "Notes",
    .noteStyles: "Le style texte liste les comptes déjà lus. Le pourcentage est ce qu’il reste, et l’heure est celle de la réinitialisation. L’orange et le rouge indiquent une fenêtre bientôt épuisée.",
    .notePrivacy: "La connexion n’est lue que sur ce Mac, uniquement pour vérifier la consommation. L’app ne réécrit pas les jetons et n’envoie pas le contenu des conversations.",
    .noteAccounts: "ChatGPT lit la connexion déjà enregistrée par l’app ChatGPT, puis interroge le site officiel. Cursor utilise la connexion Cursor actuelle. Les fenêtres Claude de 5 heures et de 7 jours exigent une connexion d’abonnement. Une clé d’API seule ne les affiche pas.",
    .preview: "Aperçu",
    .addBar: "Ajouter une barre",
    .addRing: "Ajouter un anneau",
    .hintBars: "De haut en bas, c’est l’ordre des barres dans la barre des menus. Chaque barre peut être un quota ou la batterie, avec sa couleur. Six au plus.",
    .hintRings: "De gauche à droite, c’est l’ordre des petits anneaux. Chaque anneau peut être un quota ou la batterie, avec sa couleur. Six au plus.",
    .hintCombined: "De haut en bas, la première ligne est l’anneau extérieur. Chaque anneau peut être un quota ou la batterie, avec sa couleur. Six au plus.",
    .meaning: "Sens",
    .colorLabel: "Couleur",
    .styleText: "Texte",
    .styleBattery: "Batterie seule",
    .styleBars: "Barres colorées",
    .styleRing: "Anneau simple",
    .styleRings: "Anneaux multiples",
    .styleCombined: "Anneau combiné",
    .detailText: "Affiche le nom du compte, le pourcentage restant et le compte à rebours.",
    .detailBattery: "Affiche seulement la batterie de ce Mac, en icône ou en pourcentage, selon le choix ci-dessus.",
    .detailBars: "Chaque barre représente un quota. Plus elle est longue, plus il en reste. Le sens et la couleur se règlent.",
    .detailRing: "Ne garde que la fenêtre la plus tendue, avec un anneau et un pourcentage, sans le nom du compte.",
    .detailRings: "Chaque quota a son petit anneau, côte à côte. Le sens et la couleur sont ceux des barres colorées.",
    .detailCombined: "Dessine ces quotas en anneaux concentriques dans une seule icône. La première ligne est l’anneau extérieur.",
    .batteryPercent: "Batterie %d%%",
    .charging: "En charge",
    .onBattery: "Sur batterie",
    .noBatteryDevice: "Ce Mac n’a pas de batterie.",
    .noBatteryShort: "Sans batterie",
    .batteryChargingHelp: "Batterie %d%%, en charge",
    .batteryIdleHelp: "Batterie %d%%",
    .exhausted: "%@ est épuisé. Cette fenêtre reste indisponible jusqu’à la réinitialisation.",
    .creditsLine: "Crédits %@",
    .remainingWord: "reste",
    .noReset: "Pas encore d’heure de réinitialisation",
    .usedLine: "Utilisé %d%%",
    .helpLeft: "%@ : %d%% restants",
    .helpLeftReset: "%@ : %d%% restants, réinitialisation %@",
    .accountLine: "%@ : %@",
    .noUsageYet: "Pas encore de consommation",
    .resetSoon: "bientôt réinitialisé",
    .shortDH: "%d j %d h",
    .shortHM: "%d h %d min",
    .shortM: "%d min",
    .longDH: "Réinitialisation dans %d j %d h",
    .longHM: "Réinitialisation dans %d h %d min",
    .longM: "Réinitialisation dans %d min",
    .todayAt: "Aujourd’hui %@",
    .tomorrowAt: "Demain %@",
    .dateAt: "%@ %@",
    .justNow: "Mis à jour à l’instant",
    .secsAgo: "Mis à jour il y a %d s",
    .minsAgo: "Mis à jour il y a %d min",
    .hoursAgo: "Mis à jour il y a %d h",
    .daysAgo: "Mis à jour il y a %d j",
    .fiveHours: "5 heures",
    .sevenDays: "7 jours",
    .hours24: "24 heures",
    .nDays: "%d jours",
    .nHours: "%d heures",
    .thisMonth: "Ce mois-ci",
    .onDemand: "À la demande",
    .monthRequests: "Requêtes du mois",
    .opusWeek: "Opus hebdomadaire",
    .sonnetWeek: "Sonnet hebdomadaire",
    .haikuWeek: "Haiku hebdomadaire",
    .extraUsage: "Usage supplémentaire",
    .shortWindow: "Fenêtre courte",
    .longWindow: "Fenêtre longue",
    .otherQuota: "Autre quota",
    .batteryName: "Batterie",
    .noBatteryData: "Pas encore de donnée de batterie",
    .batteryStateLine: "%d%%, %@",
    .noSlotData: "Pas encore de donnée",
    .remainLine: "%d%% restants",
    .unlimited: "Illimité",
    .localNote: "D’après les enregistrements locaux",
    .dollarNote: "Usage inclus %@ USD, plafond %@ USD",
    .alertTitle: "Peu de quota %@",
    .alertBody: "%@ : %d%% restants, %@.",
    .alertBodyPlain: "%@ : %d%% restants.",
    .reading: "Lecture",
    .official: "Consommation officielle",
    .localCodex: "Le site officiel n’a pas encore renvoyé la consommation, donc les derniers chiffres enregistrés sur ce Mac sont affichés.",
    .noUsageCodex: "Pas encore de consommation. Ouvrez l’app ChatGPT et connectez-vous.",
    .gptUnauthorized: "La connexion n’est plus valable. Ouvrez Codex une fois et laissez-le rafraîchir la connexion. Cette app ne réécrit pas le fichier de connexion.",
    .gptExpired: "La connexion a expiré. Ouvrez Codex une fois, laissez-le rafraîchir la connexion, puis réessayez. Cette app ne réécrit pas le fichier de connexion.",
    .gptMissing: "L’app ChatGPT n’a pas encore de connexion enregistrée. Ouvrez ChatGPT et connectez-vous.",
    .gptAPIKey: "C’est une connexion par clé d’API, sans fenêtre d’abonnement ChatGPT. Utilisez codex login.",
    .gptUnreadable: "Le fichier de connexion local ne peut pas être lu.",
    .gptHTTP: "Le service a renvoyé %d. Affichage de l’enregistrement local pour l’instant.",
    .gptTemporary: "La consommation officielle est illisible pour l’instant. Affichage de l’enregistrement local.",
    .gptOffline: "Pas de réseau. Affichage de l’enregistrement local pour l’instant.",
    .gptTimeout: "Le service a expiré. Affichage de l’enregistrement local pour l’instant.",
    .gptUnreachable: "Le service est injoignable. Affichage de l’enregistrement local pour l’instant.",
    .cursorNoLogin: "Aucune connexion Cursor n’a été trouvée. Connectez-vous d’abord dans Cursor.",
    .cursorEmpty: "La connexion est valable, mais le service n’a renvoyé aucune fenêtre.",
    .cursorUnauthorized: "La connexion Cursor n’est plus valable. Reconnectez-vous dans Cursor. Cette app ne modifie pas la connexion.",
    .cursorHTTP: "Le service Cursor a renvoyé %d.",
    .cursorTemporary: "La consommation Cursor est illisible pour l’instant.",
    .cursorOffline: "Pas de réseau. La consommation Cursor est illisible pour l’instant.",
    .cursorTimeout: "Le service Cursor a expiré.",
    .cursorUnreachable: "Le service Cursor est injoignable pour l’instant.",
    .claudeUnauthorized: "La connexion Claude n’est plus valable. Ouvrez Claude Code une fois et laissez-le rafraîchir la connexion. Cette app ne modifie pas la connexion.",
    .claudeExpired: "La connexion Claude a expiré. Ouvrez Claude Code une fois et laissez-le rafraîchir la connexion. Cette app ne modifie pas la connexion.",
    .claudeAPIKey: "Une clé d’API a été détectée. Il n’y a pas de fenêtre d’abonnement Claude de 5 heures ni de 7 jours. Connectez un compte d’abonnement avec claude.",
    .claudeMissing: "Il n’y a pas encore de connexion d’abonnement Claude. Lancez claude dans le Terminal et connectez-vous. Les fenêtres de 5 heures et de 7 jours apparaîtront ici.",
    .claudeUnreadable: "Le fichier de connexion Claude ne peut pas être lu.",
    .claude429: "Le service Claude limite le débit. Réessayez dans quelques minutes.",
    .claudeHTTP: "Le service Claude a renvoyé %d.",
    .claudeTemporary: "La consommation Claude est illisible pour l’instant.",
    .claudeOffline: "Pas de réseau. La consommation Claude est illisible pour l’instant.",
    .claudeTimeout: "Le service Claude a expiré.",
    .claudeUnreachable: "Le service Claude est injoignable pour l’instant.",
    .listSep: ", ",
    .pair: "%@ · %@"
]

private let es: [LKey: String] = [
    .checkingUpdates: "Buscando versiones…",
    .updateAvailable: "La versión %@ está disponible.",
    .upToDate: "Tienes la última versión publicada o una compilación más reciente.",
    .updateCheckFailed: "No se pudo buscar actualizaciones. Puedes consultar las versiones manualmente.",
    .openRelease: "Abrir versiones",
    .pausedUpdates: "Actualizaciones pausadas",
    .staleReading: "Lectura anterior",
    .unavailable: "Datos no disponibles",
    .lastAttempt: "Último intento: %@",
    .formatChanged: "El formato de la respuesta ha cambiado. Consulta la ayuda de inicio de sesión o informa del problema de compatibilidad.",
    .cursorConflict: "El mensaje de Cursor difiere del presupuesto numérico. Se muestran los campos numéricos.",
    .providerHelp: "Activa cada servicio por separado. Los servicios pausados conservan su última lectura en el panel y se ocultan en los indicadores de cuota de la barra de menús. La actualización manual también respeta estos ajustes.",
    .loginHelp: "Ayuda para iniciar sesión",
    .diagnostics: "Exportar diagnóstico…",
    .diagnosticsHelp: "Exporta estados, horas y cantidades de ventanas. No incluye tokens, identificadores de cuenta, correos, conversaciones ni valores de uso.",
    .welcomeTitle: "Bienvenido a MacTokenGauge",
    .welcomeHelp: "Elige los servicios que utilizas. ChatGPT lee CODEX_HOME/auth.json, normalmente ~/.codex/auth.json; Cursor lee su base de datos local; Claude lee las credenciales locales o el llavero. Los tokens solo se envían al servicio correspondiente. Los registros de Codex deben identificar explícitamente la cuenta actual. No se modifican archivos de inicio de sesión.",
    .getStarted: "Comenzar",
    .releases: "Buscar actualizaciones…",
    .settingsWindow: "MacTokenGauge",
    .settings: "Ajustes",
    .closeWindow: "Cerrar ventana",
    .quit: "Salir",
    .usage: "Uso",
    .usageSubtitle: "ChatGPT, Cursor y Claude se muestran juntos. El porcentaje es lo que queda.",
    .refreshHelp: "Volver a leer el uso",
    .sectionData: "Datos",
    .liveToggle: "Leer el uso oficial",
    .liveHelp: "ChatGPT consulta el sitio oficial en este intervalo y conserva esa cifra. Los registros locales solo aparecen antes de que el sitio haya devuelto un número. El interruptor sigue controlando Cursor y Claude.",
    .refreshInterval: "Intervalo",
    .refreshOnWake: "Actualizar al encender la pantalla",
    .refreshOnWakeHelp: "También consulta el uso cuando la pantalla se enciende, incluso al abrir la tapa. Al abrir la app siempre hay una consulta, esté o no activado.",
    .minutesValue: "%d min",
    .sectionMenu: "Barra de menús",
    .iconStyle: "Estilo del icono",
    .showBattery: "Mostrar la batería de este Mac",
    .batteryHelp: "Siempre que la barra muestre la batería, elija el icono o el porcentaje. El panel muestra ambos.",
    .batteryInterval: "Revisión de la batería",
    .batteryIntervalHelp: "Cada cuánto se lee el porcentaje de batería.",
    .powerSaverOn: "El modo de bajo consumo o el aviso de batería baja está activo. Las consultas de uso, el reloj de la barra y la lectura de la batería van más lentos hasta que termine.",
    .textTemplateLabel: "Texto de la barra",
    .textTemplateHelp: "Escriba el texto usted mismo. {name} es la cuenta, {percent} lo que queda, {countdown} el tiempo hasta el reinicio, {window} el nombre de la cuota y {reset} la hora. Cada cuenta ya leída usa este texto.",
    .tokenName: "Cuenta",
    .tokenPercent: "Restante",
    .tokenCountdown: "Cuenta atrás",
    .tokenWindow: "Ventana",
    .tokenReset: "Hora",
    .batteryChoice: "La batería muestra",
    .batteryIconOnly: "Solo el icono",
    .batteryPercentOnly: "Solo el porcentaje",
    .sectionPlace: "Posición",
    .placeLabel: "Posición del icono",
    .placeRight: "Derecha",
    .placeLeft: "Izquierda",
    .placeFarRight: "Extremo derecho",
    .placeFarLeft: "Extremo izquierdo",
    .placeHelp: "El reloj, el Centro de control, el Wi-Fi y otras apps ya ocupan la derecha. Esta app no puede apartarlos. Mantenga pulsada la tecla Comando y arrastre este icono para colocarlo entre las otras apps. Lo más a la derecha es justo a la izquierda del Centro de control.",
    .sectionAlert: "Avisos",
    .alertToggle: "Avisar cuando quede poco",
    .alertLevel: "Umbral de aviso",
    .alertHelp: "Cuando una ventana baja a esta parte restante y todavía queda algo, llega un aviso una sola vez. Si una lectura encuentra la ventana ya agotada, no hay aviso. No se repite en el mismo ciclo.",
    .launchLogin: "Abrir al iniciar sesión",
    .launchOn: "Se abrirá al iniciar sesión. Si el sistema lo impide, mueva la app a la carpeta Aplicaciones y vuelva a intentarlo.",
    .launchDenied: "El sistema no permitió abrirla al iniciar sesión: %@",
    .sectionLanguage: "Idioma",
    .languageLabel: "Idioma de la interfaz",
    .followSystem: "Seguir el sistema",
    .languageHelp: "Seguir el sistema usa árabe, chino, inglés, francés, ruso o español si ese es el idioma del Mac. Si no, usa inglés. También puede elegir aquí uno de los seis idiomas oficiales de las Naciones Unidas.",
    .sectionNotes: "Notas",
    .noteStyles: "El estilo de texto enumera las cuentas ya leídas. El porcentaje es lo que queda, y la hora es la del reinicio. El naranja y el rojo indican que la ventana se está agotando.",
    .notePrivacy: "El inicio de sesión solo se lee en este Mac, y solo para consultar el uso. La app no reescribe los tokens ni envía el contenido de las conversaciones.",
    .noteAccounts: "ChatGPT lee el inicio de sesión que la app ChatGPT ya guardó y luego consulta el sitio oficial. Cursor usa el inicio de sesión actual de Cursor. Las ventanas de 5 horas y 7 días de Claude necesitan un inicio de sesión de suscripción. Una clave de API sola no las muestra.",
    .preview: "Vista previa",
    .addBar: "Añadir una barra",
    .addRing: "Añadir un anillo",
    .hintBars: "De arriba abajo es el orden de las barras en la barra de menús. Cada barra puede ser una cuota o la batería, con su color. Hasta seis.",
    .hintRings: "De izquierda a derecha es el orden de los anillos pequeños. Cada anillo puede ser una cuota o la batería, con su color. Hasta seis.",
    .hintCombined: "De arriba abajo, la primera fila es el anillo exterior. Cada anillo puede ser una cuota o la batería, con su color. Hasta seis.",
    .meaning: "Significado",
    .colorLabel: "Color",
    .styleText: "Texto",
    .styleBattery: "Solo batería",
    .styleBars: "Barras de color",
    .styleRing: "Anillo único",
    .styleRings: "Varios anillos",
    .styleCombined: "Anillo combinado",
    .detailText: "Muestra el nombre de la cuenta, el porcentaje restante y la cuenta atrás.",
    .detailBattery: "Muestra solo la batería de este Mac, como icono o como porcentaje, según la opción de arriba.",
    .detailBars: "Cada barra es una cuota. Cuanto más larga, más queda. Puede cambiar el significado y el color.",
    .detailRing: "Deja solo la ventana más ajustada, con un anillo y un porcentaje, sin el nombre de la cuenta.",
    .detailRings: "Cada cuota tiene su anillo pequeño, en fila. El significado y el color son los de las barras de color.",
    .detailCombined: "Dibuja esas cuotas como anillos concéntricos en un solo icono. La primera fila es el anillo exterior.",
    .batteryPercent: "Batería %d%%",
    .charging: "Cargando",
    .onBattery: "Con batería",
    .noBatteryDevice: "Este Mac no tiene batería.",
    .noBatteryShort: "Sin batería",
    .batteryChargingHelp: "Batería %d%%, cargando",
    .batteryIdleHelp: "Batería %d%%",
    .exhausted: "%@ se ha agotado. Esa ventana no se puede usar hasta la hora de reinicio.",
    .creditsLine: "Créditos %@",
    .remainingWord: "queda",
    .noReset: "Aún no hay hora de reinicio",
    .usedLine: "Usado %d%%",
    .helpLeft: "A %@ le queda %d%%",
    .helpLeftReset: "A %@ le queda %d%%, se reinicia %@",
    .accountLine: "%@: %@",
    .noUsageYet: "Aún no hay uso",
    .resetSoon: "se reinicia pronto",
    .shortDH: "%d d %d h",
    .shortHM: "%d h %d min",
    .shortM: "%d min",
    .longDH: "Se reinicia en %d d %d h",
    .longHM: "Se reinicia en %d h %d min",
    .longM: "Se reinicia en %d min",
    .todayAt: "Hoy %@",
    .tomorrowAt: "Mañana %@",
    .dateAt: "%@ %@",
    .justNow: "Actualizado ahora",
    .secsAgo: "Actualizado hace %d s",
    .minsAgo: "Actualizado hace %d min",
    .hoursAgo: "Actualizado hace %d h",
    .daysAgo: "Actualizado hace %d d",
    .fiveHours: "5 horas",
    .sevenDays: "7 días",
    .hours24: "24 horas",
    .nDays: "%d días",
    .nHours: "%d horas",
    .thisMonth: "Este mes",
    .onDemand: "Bajo demanda",
    .monthRequests: "Solicitudes del mes",
    .opusWeek: "Opus semanal",
    .sonnetWeek: "Sonnet semanal",
    .haikuWeek: "Haiku semanal",
    .extraUsage: "Uso extra",
    .shortWindow: "Ventana corta",
    .longWindow: "Ventana larga",
    .otherQuota: "Otra cuota",
    .batteryName: "Batería",
    .noBatteryData: "Aún no hay datos de batería",
    .batteryStateLine: "%d%%, %@",
    .noSlotData: "Aún no hay datos",
    .remainLine: "Queda %d%%",
    .unlimited: "Ilimitado",
    .localNote: "De los registros locales",
    .dollarNote: "Uso incluido %@ USD, límite %@ USD",
    .alertTitle: "Queda poco de %@",
    .alertBody: "A %@ le queda %d%%, %@.",
    .alertBodyPlain: "A %@ le queda %d%%.",
    .reading: "Leyendo",
    .official: "Uso oficial",
    .localCodex: "El sitio oficial aún no ha devuelto el uso, así que se muestran las últimas cifras guardadas en este Mac.",
    .noUsageCodex: "Aún no hay uso. Abra la app ChatGPT e inicie sesión.",
    .gptUnauthorized: "La sesión ya no es válida. Abra Codex una vez y deje que renueve la sesión. Esta app no reescribe el archivo de sesión.",
    .gptExpired: "La sesión ha caducado. Abra Codex una vez, deje que la renueve y vuelva a intentarlo. Esta app no reescribe el archivo de sesión.",
    .gptMissing: "La app ChatGPT aún no tiene un inicio de sesión guardado. Abra ChatGPT e inicie sesión.",
    .gptAPIKey: "Es una sesión con clave de API, sin ventana de suscripción de ChatGPT. Use codex login.",
    .gptUnreadable: "No se puede leer el archivo de sesión local.",
    .gptHTTP: "El servicio devolvió %d. Se muestra el registro local por ahora.",
    .gptTemporary: "Ahora no se puede leer el uso oficial. Se muestra el registro local.",
    .gptOffline: "No hay red. Se muestra el registro local por ahora.",
    .gptTimeout: "El servicio agotó el tiempo. Se muestra el registro local por ahora.",
    .gptUnreachable: "No se puede conectar con el servicio. Se muestra el registro local por ahora.",
    .cursorNoLogin: "No se encontró una sesión de Cursor. Inicie sesión primero en Cursor.",
    .cursorEmpty: "La sesión es válida, pero el servicio no devolvió ventanas.",
    .cursorUnauthorized: "La sesión de Cursor ya no es válida. Vuelva a iniciar sesión en Cursor. Esta app no cambia la sesión.",
    .cursorHTTP: "El servicio de Cursor devolvió %d.",
    .cursorTemporary: "Ahora no se puede leer el uso de Cursor.",
    .cursorOffline: "No hay red. Ahora no se puede leer el uso de Cursor.",
    .cursorTimeout: "El servicio de Cursor agotó el tiempo.",
    .cursorUnreachable: "Ahora no se puede conectar con el servicio de Cursor.",
    .claudeUnauthorized: "La sesión de Claude ya no es válida. Abra Claude Code una vez y deje que renueve la sesión. Esta app no cambia la sesión.",
    .claudeExpired: "La sesión de Claude ha caducado. Abra Claude Code una vez y deje que renueve la sesión. Esta app no cambia la sesión.",
    .claudeAPIKey: "Se detectó una clave de API. No hay ventana de suscripción de Claude de 5 horas ni de 7 días. Inicie sesión en una cuenta de suscripción con claude.",
    .claudeMissing: "Aún no hay sesión de suscripción de Claude. Ejecute claude en Terminal e inicie sesión. Aquí aparecerán las ventanas de 5 horas y de 7 días.",
    .claudeUnreadable: "No se puede leer el archivo de sesión de Claude.",
    .claude429: "El servicio de Claude está limitando las peticiones. Actualice dentro de unos minutos.",
    .claudeHTTP: "El servicio de Claude devolvió %d.",
    .claudeTemporary: "Ahora no se puede leer el uso de Claude.",
    .claudeOffline: "No hay red. Ahora no se puede leer el uso de Claude.",
    .claudeTimeout: "El servicio de Claude agotó el tiempo.",
    .claudeUnreachable: "Ahora no se puede conectar con el servicio de Claude.",
    .listSep: ", ",
    .pair: "%@ · %@"
]

private let ru: [LKey: String] = [
    .checkingUpdates: "Проверка обновлений…",
    .updateAvailable: "Доступна версия %@.",
    .upToDate: "У вас последняя опубликованная версия или более новая сборка.",
    .updateCheckFailed: "Не удалось проверить обновления. Можно открыть страницу выпусков вручную.",
    .openRelease: "Открыть выпуски",
    .pausedUpdates: "Обновление приостановлено",
    .staleReading: "Предыдущее значение",
    .unavailable: "Данные недоступны",
    .lastAttempt: "Последняя попытка: %@",
    .formatChanged: "Формат ответа изменился. Посмотрите справку по входу или сообщите о проблеме совместимости.",
    .cursorConflict: "Текст Cursor расходится с числовыми данными бюджета. Показаны числовые данные.",
    .providerHelp: "Включайте сервисы отдельно. Приостановленные сервисы сохраняют последнее значение в панели и скрываются из индикаторов квоты в строке меню. Ручное обновление также учитывает эти переключатели.",
    .loginHelp: "Помощь со входом",
    .diagnostics: "Экспорт диагностики…",
    .diagnosticsHelp: "Экспортируются состояния, время и количество окон. Токены, идентификаторы аккаунтов, почта, разговоры и значения использования не включаются.",
    .welcomeTitle: "Добро пожаловать в MacTokenGauge",
    .welcomeHelp: "Выберите используемые сервисы. ChatGPT читает CODEX_HOME/auth.json, обычно ~/.codex/auth.json; Cursor читает локальную базу; Claude читает локальные учётные данные или Связку ключей. Каждый токен отправляется только соответствующему сервису. Журналы Codex должны явно указывать текущий аккаунт. Файлы входа не изменяются.",
    .getStarted: "Начать",
    .releases: "Проверить обновления…",
    .settingsWindow: "MacTokenGauge",
    .settings: "Настройки",
    .closeWindow: "Закрыть окно",
    .quit: "Выйти",
    .usage: "Расход",
    .usageSubtitle: "ChatGPT, Cursor и Claude показаны вместе. Процент — это остаток.",
    .refreshHelp: "Прочитать расход снова",
    .sectionData: "Данные",
    .liveToggle: "Читать официальный расход",
    .liveHelp: "ChatGPT с этим интервалом читает официальный сайт и сохраняет эту цифру. Локальные записи видны только пока сайт ещё ничего не вернул. Переключатель по-прежнему управляет Cursor и Claude.",
    .refreshInterval: "Интервал",
    .refreshOnWake: "Обновлять при включении экрана",
    .refreshOnWakeHelp: "Также запрашивает расход, когда экран включается, в том числе при открытии крышки. При запуске приложения запрос выполняется всегда, независимо от этого переключателя.",
    .minutesValue: "%d мин",
    .sectionMenu: "Строка меню",
    .iconStyle: "Вид значка",
    .showBattery: "Показывать батарею этого Mac",
    .batteryHelp: "Когда в строке меню видна батарея, можно показать только значок или только процент. В панели остаются оба.",
    .batteryInterval: "Проверка батареи",
    .batteryIntervalHelp: "Как часто читается процент заряда.",
    .powerSaverOn: "Включён режим энергосбережения или предупреждение о низком заряде. Проверка расхода, часы в строке меню и чтение батареи замедляются, пока это не закончится.",
    .textTemplateLabel: "Текст в строке меню",
    .textTemplateHelp: "Текст можно написать самому. {name} — учётная запись, {percent} — остаток, {countdown} — время до сброса, {window} — название квоты, {reset} — час сброса. Каждая уже прочитанная учётная запись использует этот текст.",
    .tokenName: "Аккаунт",
    .tokenPercent: "Остаток",
    .tokenCountdown: "Отсчёт",
    .tokenWindow: "Окно",
    .tokenReset: "Время",
    .batteryChoice: "Батарея показывает",
    .batteryIconOnly: "Только значок",
    .batteryPercentOnly: "Только процент",
    .sectionPlace: "Положение",
    .placeLabel: "Положение значка",
    .placeRight: "Справа",
    .placeLeft: "Слева",
    .placeFarRight: "Крайний правый",
    .placeFarLeft: "Крайний левый",
    .placeHelp: "Часы, Пункт управления, Wi-Fi и другие приложения уже занимают правую сторону. Это приложение не может их сдвинуть. Удерживайте Command и перетащите значок, чтобы поставить его среди других. Дальше всего он встаёт сразу слева от Пункта управления.",
    .sectionAlert: "Оповещения",
    .alertToggle: "Сообщать, когда осталось мало",
    .alertLevel: "Порог оповещения",
    .alertHelp: "Когда у окна остаток падает до этой доли и квота ещё не кончилась, приходит одно уведомление. Если проверка застаёт окно уже пустым, уведомления нет. В том же цикле оно не повторяется.",
    .launchLogin: "Открывать при входе",
    .launchOn: "Приложение будет открываться при входе. Если система не позволит, перенесите его в папку «Программы» и попробуйте снова.",
    .launchDenied: "Система не разрешила открытие при входе: %@",
    .sectionLanguage: "Язык",
    .languageLabel: "Язык интерфейса",
    .followSystem: "Как в системе",
    .languageHelp: "Режим «как в системе» выбирает арабский, китайский, английский, французский, русский или испанский, если это язык Mac. Иначе используется английский. Здесь можно выбрать один из шести официальных языков ООН.",
    .sectionNotes: "Пояснение",
    .noteStyles: "Текстовый вид перечисляет уже прочитанные учётные записи. Процент — это остаток, а время — момент сброса. Оранжевый и красный означают, что окно на исходе.",
    .notePrivacy: "Вход читается только на этом Mac и только для проверки расхода. Приложение не записывает токены обратно и не отправляет содержимое разговоров.",
    .noteAccounts: "ChatGPT читает вход, уже сохранённый приложением ChatGPT, и затем спрашивает официальный сайт. Cursor использует текущий вход Cursor. Окна Claude на 5 часов и 7 дней требуют входа по подписке. Одного ключа API недостаточно.",
    .preview: "Просмотр",
    .addBar: "Добавить полосу",
    .addRing: "Добавить кольцо",
    .hintBars: "Сверху вниз — порядок полос в строке меню. Каждая полоса может быть квотой или батареей, со своим цветом. Не больше шести.",
    .hintRings: "Слева направо — порядок маленьких колец. Каждое кольцо может быть квотой или батареей, со своим цветом. Не больше шести.",
    .hintCombined: "Сверху вниз первая строка — внешнее кольцо. Каждое кольцо может быть квотой или батареей, со своим цветом. Не больше шести.",
    .meaning: "Смысл",
    .colorLabel: "Цвет",
    .styleText: "Текст",
    .styleBattery: "Только батарея",
    .styleBars: "Цветные полосы",
    .styleRing: "Одно кольцо",
    .styleRings: "Несколько колец",
    .styleCombined: "Общее кольцо",
    .detailText: "Показывает имя учётной записи, оставшийся процент и отсчёт до сброса.",
    .detailBattery: "В строке меню только батарея этого Mac, значком или процентом, по выбору выше.",
    .detailBars: "Каждая полоса — одна квота. Чем длиннее полоса, тем больше остаток. Смысл и цвет можно задать.",
    .detailRing: "Оставляет только самое напряжённое окно: одно кольцо и процент, без имени учётной записи.",
    .detailRings: "У каждой квоты своё маленькое кольцо в ряд. Смысл и цвет общие с цветными полосами.",
    .detailCombined: "Рисует эти квоты концентрическими кольцами в одном значке. Первая строка — внешнее кольцо.",
    .batteryPercent: "Батарея %d%%",
    .charging: "Заряжается",
    .onBattery: "От батареи",
    .noBatteryDevice: "У этого Mac нет батареи.",
    .noBatteryShort: "Нет батареи",
    .batteryChargingHelp: "Батарея %d%%, заряжается",
    .batteryIdleHelp: "Батарея %d%%",
    .exhausted: "%@ исчерпано. До времени сброса это окно недоступно.",
    .creditsLine: "Кредиты %@",
    .remainingWord: "осталось",
    .noReset: "Времени сброса пока нет",
    .usedLine: "Использовано %d%%",
    .helpLeft: "%@: осталось %d%%",
    .helpLeftReset: "%@: осталось %d%%, сброс %@",
    .accountLine: "%@: %@",
    .noUsageYet: "Расход ещё не прочитан",
    .resetSoon: "скоро сброс",
    .shortDH: "%d д %d ч",
    .shortHM: "%d ч %d мин",
    .shortM: "%d мин",
    .longDH: "Сброс через %d д %d ч",
    .longHM: "Сброс через %d ч %d мин",
    .longM: "Сброс через %d мин",
    .todayAt: "Сегодня %@",
    .tomorrowAt: "Завтра %@",
    .dateAt: "%@ %@",
    .justNow: "Только что обновлено",
    .secsAgo: "Обновлено %d с назад",
    .minsAgo: "Обновлено %d мин назад",
    .hoursAgo: "Обновлено %d ч назад",
    .daysAgo: "Обновлено %d д назад",
    .fiveHours: "5 часов",
    .sevenDays: "7 дней",
    .hours24: "24 часа",
    .nDays: "%d дн.",
    .nHours: "%d ч",
    .thisMonth: "Этот месяц",
    .onDemand: "По потреблению",
    .monthRequests: "Запросы за месяц",
    .opusWeek: "Opus за неделю",
    .sonnetWeek: "Sonnet за неделю",
    .haikuWeek: "Haiku за неделю",
    .extraUsage: "Дополнительный расход",
    .shortWindow: "Короткое окно",
    .longWindow: "Длинное окно",
    .otherQuota: "Другая квота",
    .batteryName: "Батарея",
    .noBatteryData: "Данных батареи пока нет",
    .batteryStateLine: "%d%%, %@",
    .noSlotData: "Данных пока нет",
    .remainLine: "Осталось %d%%",
    .unlimited: "Без лимита",
    .localNote: "Из локальных записей",
    .dollarNote: "Включённый расход %@ USD, предел %@ USD",
    .alertTitle: "Мало квоты %@",
    .alertBody: "%@: осталось %d%%, %@.",
    .alertBodyPlain: "%@: осталось %d%%.",
    .reading: "Чтение",
    .official: "Официальный расход",
    .localCodex: "Официальный сайт ещё не вернул расход, поэтому показаны последние цифры, сохранённые на этом Mac.",
    .noUsageCodex: "Расход ещё не прочитан. Откройте приложение ChatGPT и войдите.",
    .gptUnauthorized: "Вход больше не действителен. Откройте Codex один раз и дайте ему обновить вход. Это приложение не переписывает файл входа.",
    .gptExpired: "Срок входа истёк. Откройте Codex один раз, дайте ему обновить вход и попробуйте снова. Это приложение не переписывает файл входа.",
    .gptMissing: "У приложения ChatGPT ещё нет сохранённого входа. Откройте ChatGPT и войдите.",
    .gptAPIKey: "Это вход по ключу API, без окна подписки ChatGPT. Используйте codex login.",
    .gptUnreadable: "Локальный файл входа не читается.",
    .gptHTTP: "Служба вернула %d. Пока показана локальная запись.",
    .gptTemporary: "Официальный расход сейчас не прочитать. Пока показана локальная запись.",
    .gptOffline: "Нет сети. Пока показана локальная запись.",
    .gptTimeout: "Служба не ответила вовремя. Пока показана локальная запись.",
    .gptUnreachable: "Служба сейчас недоступна. Пока показана локальная запись.",
    .cursorNoLogin: "Вход Cursor не найден. Сначала войдите в Cursor.",
    .cursorEmpty: "Вход действителен, но служба не вернула окна.",
    .cursorUnauthorized: "Вход Cursor больше не действителен. Войдите в Cursor снова. Это приложение не меняет вход.",
    .cursorHTTP: "Служба Cursor вернула %d.",
    .cursorTemporary: "Расход Cursor сейчас не прочитать.",
    .cursorOffline: "Нет сети. Расход Cursor сейчас не прочитать.",
    .cursorTimeout: "Служба Cursor не ответила вовремя.",
    .cursorUnreachable: "Служба Cursor сейчас недоступна.",
    .claudeUnauthorized: "Вход Claude больше не действителен. Откройте Claude Code один раз и дайте ему обновить вход. Это приложение не меняет вход.",
    .claudeExpired: "Срок входа Claude истёк. Откройте Claude Code один раз и дайте ему обновить вход. Это приложение не меняет вход.",
    .claudeAPIKey: "Найден ключ API. Нет окон подписки Claude на 5 часов и 7 дней. Войдите в учётную запись подписки командой claude.",
    .claudeMissing: "Входа по подписке Claude ещё нет. Выполните claude в Терминале и войдите. Здесь появятся окна на 5 часов и 7 дней.",
    .claudeUnreadable: "Файл входа Claude не читается.",
    .claude429: "Служба Claude ограничивает запросы. Обновите через несколько минут.",
    .claudeHTTP: "Служба Claude вернула %d.",
    .claudeTemporary: "Расход Claude сейчас не прочитать.",
    .claudeOffline: "Нет сети. Расход Claude сейчас не прочитать.",
    .claudeTimeout: "Служба Claude не ответила вовремя.",
    .claudeUnreachable: "Служба Claude сейчас недоступна.",
    .listSep: ", ",
    .pair: "%@ · %@"
]

private let ar: [LKey: String] = [
    .checkingUpdates: "جارٍ البحث عن تحديثات…",
    .updateAvailable: "الإصدار %@ متاح.",
    .upToDate: "لديك أحدث إصدار منشور أو نسخة أحدث.",
    .updateCheckFailed: "تعذر البحث عن تحديثات. يمكنك فتح صفحة الإصدارات يدويًا.",
    .openRelease: "فتح الإصدارات",
    .pausedUpdates: "التحديثات متوقفة مؤقتًا",
    .staleReading: "قراءة سابقة",
    .unavailable: "البيانات غير متاحة",
    .lastAttempt: "آخر محاولة: %@",
    .formatChanged: "تغير تنسيق استجابة الاستخدام. راجع مساعدة تسجيل الدخول أو أبلغ عن مشكلة التوافق.",
    .cursorConflict: "تختلف رسالة Cursor عن بيانات الميزانية الرقمية. تُعرض البيانات الرقمية.",
    .providerHelp: "فعّل كل خدمة على حدة. تحتفظ الخدمات المتوقفة بآخر قراءة في اللوحة وتُخفى من مؤشرات الحصة في شريط القوائم. يحترم التحديث اليدوي هذه الخيارات أيضًا.",
    .loginHelp: "مساعدة تسجيل الدخول",
    .diagnostics: "تصدير معلومات التشخيص…",
    .diagnosticsHelp: "يُصدّر حالات الخدمات والأوقات وعدد النوافذ فقط، دون رموز الدخول أو معرفات الحسابات أو البريد أو المحادثات أو قيم الاستخدام.",
    .welcomeTitle: "مرحبًا بك في MacTokenGauge",
    .welcomeHelp: "اختر الخدمات التي تستخدمها. يقرأ ChatGPT ملف CODEX_HOME/auth.json، وعادةً ~/.codex/auth.json؛ ويقرأ Cursor قاعدة بياناته المحلية؛ ويقرأ Claude بيانات الدخول المحلية أو سلسلة المفاتيح. يُرسل كل رمز إلى خدمته فقط. لا تُستخدم سجلات Codex إلا إذا حددت الحساب الحالي صراحةً. لا تُعدّل ملفات الدخول.",
    .getStarted: "ابدأ الاستخدام",
    .releases: "البحث عن تحديثات…",
    .settingsWindow: "MacTokenGauge",
    .settings: "الإعدادات",
    .closeWindow: "إغلاق النافذة",
    .quit: "إنهاء",
    .usage: "الاستخدام",
    .usageSubtitle: "تظهر ChatGPT وCursor وClaude معًا. النسبة هي المتبقي.",
    .refreshHelp: "قراءة الاستخدام من جديد",
    .sectionData: "البيانات",
    .liveToggle: "قراءة الاستخدام الرسمي",
    .liveHelp: "يتصل ChatGPT بالموقع الرسمي حسب هذه الفترة ويحتفظ بالرقم الذي يصله. لا تظهر السجلات المحلية إلا قبل أن يعيد الموقع أي قراءة. المفتاح ما زال يتحكم في Cursor وClaude.",
    .refreshInterval: "فترة التحديث",
    .refreshOnWake: "التحديث عند إضاءة الشاشة",
    .refreshOnWakeHelp: "يعيد جلب الاستخدام أيضاً عند إضاءة الشاشة، بما في ذلك فتح غطاء الجهاز. تشغيل التطبيق يجلب البيانات مرة دائماً، سواء كان هذا الخيار مفتوحاً أو مغلقاً.",
    .minutesValue: "%d د",
    .sectionMenu: "شريط القوائم",
    .iconStyle: "شكل الأيقونة",
    .showBattery: "إظهار بطارية هذا الجهاز",
    .batteryHelp: "كلما ظهرت البطارية في الشريط، يمكن اختيار الأيقونة أو النسبة فقط. اللوحة تعرض الاثنين.",
    .batteryInterval: "فحص البطارية",
    .batteryIntervalHelp: "عدد مرات قراءة نسبة البطارية.",
    .powerSaverOn: "وضع توفير الطاقة أو تنبيه انخفاض البطارية مفعّل. تتباطأ عمليات فحص الاستخدام وساعة الشريط وقراءة البطارية حتى انتهائه.",
    .textTemplateLabel: "نص شريط القوائم",
    .textTemplateHelp: "يمكن كتابة النص بنفسك. {name} هو الحساب، و{percent} هو المتبقي، و{countdown} هو الوقت حتى إعادة التعيين، و{window} هو اسم الحصة، و{reset} هو وقت الساعة. كل حساب قُرئ استخدامه يستعمل هذا النص.",
    .tokenName: "الحساب",
    .tokenPercent: "المتبقي",
    .tokenCountdown: "العد التنازلي",
    .tokenWindow: "النافذة",
    .tokenReset: "وقت الإعادة",
    .batteryChoice: "البطارية تعرض",
    .batteryIconOnly: "الأيقونة فقط",
    .batteryPercentOnly: "النسبة فقط",
    .sectionPlace: "الموضع",
    .placeLabel: "موضع الأيقونة",
    .placeRight: "اليمين",
    .placeLeft: "اليسار",
    .placeFarRight: "أقصى اليمين",
    .placeFarLeft: "أقصى اليسار",
    .placeHelp: "الساعة ومركز التحكم وشبكة Wi-Fi وتطبيقات أخرى تحتل الجهة اليمنى بالفعل. لا يستطيع هذا التطبيق إزاحتها. أبقِ مفتاح Command مضغوطًا واسحب هذه الأيقونة لترتيبها بين التطبيقات الأخرى. أبعد موضع هو مباشرة على يسار مركز التحكم.",
    .sectionAlert: "التنبيهات",
    .alertToggle: "التنبيه عند انخفاض المتبقي",
    .alertLevel: "حد التنبيه",
    .alertHelp: "عندما ينزل متبقي نافذة إلى هذه النسبة وما زال فيها شيء، يصل إشعار واحد. إذا وجد الفحص أن النافذة قد استُنفدت بالكامل، فلا إشعار. ولا يتكرر في دورة إعادة التعيين نفسها.",
    .launchLogin: "الفتح عند تسجيل الدخول",
    .launchOn: "سيُفتح التطبيق عند تسجيل الدخول. إذا منعه النظام، انقل التطبيق إلى مجلد التطبيقات ثم أعد المحاولة.",
    .launchDenied: "لم يسمح النظام بالفتح عند تسجيل الدخول: %@",
    .sectionLanguage: "اللغة",
    .languageLabel: "لغة العرض",
    .followSystem: "اتباع النظام",
    .languageHelp: "اتباع النظام يستخدم العربية أو الصينية أو الإنجليزية أو الفرنسية أو الروسية أو الإسبانية إذا كانت لغة جهاز Mac. وإلا يستخدم الإنجليزية. ويمكنك هنا اختيار إحدى اللغات الرسمية الست للأمم المتحدة.",
    .sectionNotes: "ملاحظات",
    .noteStyles: "نمط النص يسرد الحسابات التي قُرئت. النسبة هي المتبقي، والوقت هو موعد إعادة التعيين. اللون البرتقالي والأحمر يعنيان أن النافذة قاربت على النفاد.",
    .notePrivacy: "تُقرأ بيانات الدخول على هذا الجهاز فقط، ومن أجل معرفة الاستخدام. لا يعيد التطبيق كتابة الرموز، ولا يرسل محتوى المحادثات.",
    .noteAccounts: "يقرأ ChatGPT تسجيل الدخول الذي حفظه تطبيق ChatGPT، ثم يسأل الموقع الرسمي عن الاستخدام. يستخدم Cursor دخول Cursor الحالي. نافذتا Claude لخمس ساعات وسبعة أيام تحتاجان إلى دخول اشتراك. مفتاح API وحده لا يظهرهما.",
    .preview: "معاينة",
    .addBar: "إضافة خط",
    .addRing: "إضافة حلقة",
    .hintBars: "من الأعلى إلى الأسفل هو ترتيب الخطوط في شريط القوائم. يمكن لكل خط أن يمثل حصة أو البطارية، بلون مستقل. الحد ستة.",
    .hintRings: "من اليسار إلى اليمين هو ترتيب الحلقات الصغيرة. يمكن لكل حلقة أن تمثل حصة أو البطارية، بلون مستقل. الحد ست.",
    .hintCombined: "من الأعلى إلى الأسفل، الصف الأول هو الحلقة الخارجية. يمكن لكل حلقة أن تمثل حصة أو البطارية، بلون مستقل. الحد ست.",
    .meaning: "المعنى",
    .colorLabel: "اللون",
    .styleText: "نص",
    .styleBattery: "البطارية فقط",
    .styleBars: "خطوط ملونة",
    .styleRing: "حلقة واحدة",
    .styleRings: "حلقات متعددة",
    .styleCombined: "حلقة مركبة",
    .detailText: "يعرض اسم الحساب والنسبة المتبقية والعد التنازلي لإعادة التعيين.",
    .detailBattery: "يعرض بطارية هذا الجهاز فقط، كأيقونة أو كنسبة، حسب الاختيار أعلاه.",
    .detailBars: "كل خط يمثل حصة. كلما طال الخط زاد المتبقي. يمكن تغيير المعنى واللون.",
    .detailRing: "يبقي النافذة الأشد ضيقًا فقط، بحلقة ونسبة، من دون اسم الحساب.",
    .detailRings: "لكل حصة حلقة صغيرة في صف واحد. المعنى واللون مشتركان مع الخطوط الملونة.",
    .detailCombined: "يرسم هذه الحصص حلقات متحدة المركز في أيقونة واحدة. الصف الأول هو الحلقة الخارجية.",
    .batteryPercent: "البطارية %d%%",
    .charging: "قيد الشحن",
    .onBattery: "على البطارية",
    .noBatteryDevice: "لا توجد بطارية في هذا الجهاز.",
    .noBatteryShort: "لا بطارية",
    .batteryChargingHelp: "البطارية %d%%، قيد الشحن",
    .batteryIdleHelp: "البطارية %d%%",
    .exhausted: "نفد %@. تبقى هذه النافذة غير متاحة حتى وقت إعادة التعيين.",
    .creditsLine: "الرصيد %@",
    .remainingWord: "متبقٍ",
    .noReset: "لا وقت لإعادة التعيين بعد",
    .usedLine: "المستخدم %d%%",
    .helpLeft: "المتبقي من %@ هو %d%%",
    .helpLeftReset: "المتبقي من %@ هو %d%%، إعادة التعيين %@",
    .accountLine: "%@: %@",
    .noUsageYet: "لم يُقرأ استخدام بعد",
    .resetSoon: "ستتم إعادة التعيين قريبًا",
    .shortDH: "%d ي %d س",
    .shortHM: "%d س %d د",
    .shortM: "%d د",
    .longDH: "إعادة التعيين بعد %d ي %d س",
    .longHM: "إعادة التعيين بعد %d س %d د",
    .longM: "إعادة التعيين بعد %d د",
    .todayAt: "اليوم %@",
    .tomorrowAt: "غدًا %@",
    .dateAt: "%@ %@",
    .justNow: "حُدّث الآن",
    .secsAgo: "حُدّث قبل %d ث",
    .minsAgo: "حُدّث قبل %d د",
    .hoursAgo: "حُدّث قبل %d س",
    .daysAgo: "حُدّث قبل %d ي",
    .fiveHours: "5 ساعات",
    .sevenDays: "7 أيام",
    .hours24: "24 ساعة",
    .nDays: "%d أيام",
    .nHours: "%d ساعات",
    .thisMonth: "هذا الشهر",
    .onDemand: "حسب الاستخدام",
    .monthRequests: "طلبات الشهر",
    .opusWeek: "Opus أسبوعيًا",
    .sonnetWeek: "Sonnet أسبوعيًا",
    .haikuWeek: "Haiku أسبوعيًا",
    .extraUsage: "استخدام إضافي",
    .shortWindow: "نافذة قصيرة",
    .longWindow: "نافذة طويلة",
    .otherQuota: "حصة أخرى",
    .batteryName: "البطارية",
    .noBatteryData: "لا بيانات للبطارية بعد",
    .batteryStateLine: "%d%%، %@",
    .noSlotData: "لا بيانات بعد",
    .remainLine: "المتبقي %d%%",
    .unlimited: "غير محدود",
    .localNote: "من السجلات المحلية",
    .dollarNote: "الاستخدام المشمول %@ دولارًا، والحد %@ دولارًا",
    .alertTitle: "انخفاض استخدام %@",
    .alertBody: "المتبقي من %@ هو %d%%، %@.",
    .alertBodyPlain: "المتبقي من %@ هو %d%%.",
    .reading: "جارٍ القراءة",
    .official: "استخدام رسمي",
    .localCodex: "لم يعد الموقع الرسمي الاستخدام بعد، لذلك تُعرض آخر أرقام محفوظة على هذا الجهاز.",
    .noUsageCodex: "لم يُقرأ استخدام بعد. افتح تطبيق ChatGPT وسجّل الدخول.",
    .gptUnauthorized: "لم يعد تسجيل الدخول صالحًا. افتح Codex مرة واتركه يجدد الدخول بنفسه. لن يعيد هذا التطبيق كتابة ملف الدخول.",
    .gptExpired: "انتهت صلاحية تسجيل الدخول. افتح Codex مرة واتركه يجدد الدخول ثم أعد المحاولة. لن يعيد هذا التطبيق كتابة ملف الدخول.",
    .gptMissing: "لا يملك تطبيق ChatGPT تسجيل دخول محفوظًا بعد. افتح ChatGPT وسجّل الدخول.",
    .gptAPIKey: "هذا دخول بمفتاح API، ولا توجد نافذة اشتراك ChatGPT. استخدم codex login.",
    .gptUnreadable: "تعذر قراءة ملف الدخول المحلي.",
    .gptHTTP: "أعادت الخدمة %d. يُعرض السجل المحلي الآن.",
    .gptTemporary: "يتعذر الآن قراءة الاستخدام الرسمي. يُعرض السجل المحلي.",
    .gptOffline: "لا توجد شبكة. يُعرض السجل المحلي الآن.",
    .gptTimeout: "انتهت مهلة الخدمة. يُعرض السجل المحلي الآن.",
    .gptUnreachable: "يتعذر الوصول إلى الخدمة. يُعرض السجل المحلي الآن.",
    .cursorNoLogin: "لم يُعثر على دخول Cursor. سجّل الدخول داخل Cursor أولًا.",
    .cursorEmpty: "الدخول صالح، لكن الخدمة لم تُرجع أي نافذة.",
    .cursorUnauthorized: "لم يعد دخول Cursor صالحًا. سجّل الدخول من جديد داخل Cursor. لن يغيّر هذا التطبيق الدخول.",
    .cursorHTTP: "أعادت خدمة Cursor %d.",
    .cursorTemporary: "يتعذر الآن قراءة استخدام Cursor.",
    .cursorOffline: "لا توجد شبكة. يتعذر الآن قراءة استخدام Cursor.",
    .cursorTimeout: "انتهت مهلة خدمة Cursor.",
    .cursorUnreachable: "يتعذر الآن الوصول إلى خدمة Cursor.",
    .claudeUnauthorized: "لم يعد دخول Claude صالحًا. افتح Claude Code مرة واتركه يجدد الدخول. لن يغيّر هذا التطبيق الدخول.",
    .claudeExpired: "انتهت صلاحية دخول Claude. افتح Claude Code مرة واتركه يجدد الدخول. لن يغيّر هذا التطبيق الدخول.",
    .claudeAPIKey: "تم العثور على مفتاح API. لا توجد نافذة اشتراك Claude لخمس ساعات أو سبعة أيام. سجّل الدخول إلى حساب اشتراك بالأمر claude.",
    .claudeMissing: "لا يوجد بعد دخول اشتراك Claude. نفّذ claude في الطرفية وسجّل الدخول. ستظهر هنا نافذتا خمس ساعات وسبعة أيام.",
    .claudeUnreadable: "تعذر قراءة ملف دخول Claude.",
    .claude429: "خدمة Claude تحد من الطلبات مؤقتًا. حدّث بعد بضع دقائق.",
    .claudeHTTP: "أعادت خدمة Claude %d.",
    .claudeTemporary: "يتعذر الآن قراءة استخدام Claude.",
    .claudeOffline: "لا توجد شبكة. يتعذر الآن قراءة استخدام Claude.",
    .claudeTimeout: "انتهت مهلة خدمة Claude.",
    .claudeUnreachable: "يتعذر الآن الوصول إلى خدمة Claude.",
    .listSep: "، ",
    .pair: "%@ · %@"
]
